//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::learning_record::Entity as LearningRecord;
pub use super::user::Entity as User;
pub use super::word::Entity as Word;
pub use super::word_wordbook_mapping::Entity as WordWordbookMapping;
pub use super::wordbook::Entity as Wordbook;
